// Unx VGA Driver wrote by Huguini79 (https://github.com/Huguini79)

#ifndef VGA_H
#define VGA_H

#include<stdint.h>
#include<stddef.h>

// Define VGA Height and Width (80x25)
#define VGA_HEIGHT 25
#define VGA_WIDTH 80

// Define VGA struct
struct vga_struct {
	uint16_t* video_mem; // Define VGA Video Mem (16 bit data)
	uint16_t terminal_row; // Define VGA Row (height) (y)
	uint16_t terminal_col; // Define VGA Col (width) (x)
};

// Define the 16 bit function terminal_make_char to create a char and later with terminal_putchar put it in VGA Video Mem
uint16_t terminal_make_char(char c, char colour);

// Define the terminal_putchar function to put the character generated by terminal_make_char function to VGA Video Mem
void terminal_putchar(int x, int y, char c, char colour);

// Define the terminal_writechar function to write correctly in the screen with spaces etc...
void terminal_writechar(char c, char colour);

// Define the init_vga_screen to put in uint16_t* video_mem the VGA address (0xB8000)
void init_vga_screen();

// Define the size_t strlen function to know the size of an const char* variable
size_t strlen(const char* str);

// Define the printx function to write long words in one line
void printx(const char* str);

// Define the fill_screen_with_blue function
void fill_screen_with_blue();

// Define the clear function to clear the screen
void clear();

#endif
